# Generated by Django 5.0 on 2024-01-18 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0003_alter_register_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='phonenumber',
            field=models.PositiveBigIntegerField(),
        ),
    ]
